### ISSUE TITLE
[FE]제목 검색 기능 

### ISSUE THREAD

**Issue by lee-ji-hong** [course-maker/Course-Maker-BE#155]
# 개요
- 메인페이지 검색 기능 
코스라면 포함된 여행지 포함해서 검색하고, 여행지는 여행지제목

# 요청사항

- 기능 구현 시간 되면!!!!

**Comment by yunicode914** [comment]
1. 텍스트로 검색하는 기능
2. 메인페이지와 나만의 여행찾기 메뉴에서 활용
3. 코스 검색 시 : 코스제목, 코스에 포함된 여행지 이름까지 검색하여 결과 표출
4. 여행지 검색 시 : 여행지 이름 검색

- 우선 코스제목과 여행지 이름만 검색되도록! (혁진님이 ㅇㅋ함) + 코스검색시 코스에 포함된 여행지 이름까지 검색하는 기능은 나중에 시간되면
